name: monetization_kit
description: A new Flutter plugin project.
version: 1.0.9+1090
homepage: "https://github.com/LondonX/monetization_kit"
publish_to: none

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.4

  path_provider:

  visibility_detector:
  google_mobile_ads:
  flutter_inapp_purchase:
  user_messaging_platform:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        package: com.LondonX.monetization_kit
        pluginClass: MonetizationKitPlugin
      ios:
        pluginClass: MonetizationKitPlugin
