name: monetization_kit
description: A new Flutter plugin project.
version: 1.0.3+1031
homepage: "https://github.com/LondonX/monetization_kit"
publish_to: none

environment:
  sdk: ">=2.19.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.4

  path_provider:

  visibility_detector:
  google_mobile_ads: ^3.1.0
  in_app_purchase: ^3.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        package: com.LondonX.monetization_kit
        pluginClass: MonetizationKitPlugin
      ios:
        pluginClass: MonetizationKitPlugin
