name: monetization_kit
description: A new Flutter plugin project.
version: 0.0.1
homepage: "https://github.com/LondonX/monetization_kit"
publish_to: none

environment:
  sdk: '>=2.19.4 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

  visibility_detector: ^0.3.3
  google_mobile_ads: ^2.3.0

  max_ad_flutter:
    path: ./max_ad_flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.LondonX.monetization_kit
        pluginClass: MonetizationKitPlugin
      ios:
        pluginClass: MonetizationKitPlugin


